export const BOOKS_TYPES = {
  GET_BOOKS_REQUEST: "BOOKS_TYPES.GET_BOOKS_REQUEST",
  GET_BOOKS_SUCCESS: "BOOKS_TYPES.GET_BOOKS_SUCCESS",
  ORDER_BOOKS: "BOOKS_TYPES.ORDER_BOOKS",
  DELETE_BOOK: "BOOKS_TYPES.DELETE_BOOK",
};
